-- Seed data for testing the RAG system database

-- Insert sample documents
INSERT INTO documents (id, title, content, file_type, file_size, metadata) VALUES
(
  'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11',
  'Getting Started with AI',
  'Artificial Intelligence (AI) is transforming how we work and live. This document covers the basics of AI, including machine learning, deep learning, and natural language processing. AI systems can process vast amounts of data and identify patterns that humans might miss. The key to successful AI implementation is understanding your data and choosing the right algorithms for your specific use case.',
  'txt',
  512,
  '{"author": "AI Team", "category": "tutorial", "tags": ["ai", "machine-learning", "tutorial"]}'::jsonb
),
(
  'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a12',
  'Database Design Best Practices',
  'When designing databases, it is important to follow established best practices. First, normalize your data to reduce redundancy. Second, use appropriate data types for each column. Third, create indexes on frequently queried columns. Fourth, implement proper constraints to maintain data integrity. Fifth, consider performance implications of your design decisions. These practices will help ensure your database is efficient, maintainable, and scalable.',
  'txt',
  428,
  '{"author": "Database Team", "category": "best-practices", "tags": ["database", "design", "best-practices"]}'::jsonb
),
(
  'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a13',
  'Vector Databases Explained',
  'Vector databases are specialized databases designed to store and query high-dimensional vectors efficiently. They are essential for applications involving machine learning, recommendation systems, and similarity search. Popular vector databases include Pinecone, Weaviate, and Chroma. Vector databases use specialized indexing techniques like HNSW (Hierarchical Navigable Small World) and IVF (Inverted File) to enable fast similarity searches across millions of vectors.',
  'txt',
  356,
  '{"author": "Vector Team", "category": "technology", "tags": ["vector", "database", "similarity-search"]}'::jsonb
);

-- Insert sample document chunks (without embeddings for now - these would be generated by the application)
INSERT INTO document_chunks (id, document_id, chunk_index, content, token_count, metadata) VALUES
-- Chunks for "Getting Started with AI"
(
  'b0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11',
  'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11',
  0,
  'Artificial Intelligence (AI) is transforming how we work and live. This document covers the basics of AI, including machine learning, deep learning, and natural language processing.',
  32,
  '{"chunk_type": "introduction"}'::jsonb
),
(
  'b0eebc99-9c0b-4ef8-bb6d-6bb9bd380a12',
  'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11',
  1,
  'AI systems can process vast amounts of data and identify patterns that humans might miss. The key to successful AI implementation is understanding your data and choosing the right algorithms for your specific use case.',
  35,
  '{"chunk_type": "implementation"}'::jsonb
),

-- Chunks for "Database Design Best Practices"
(
  'b0eebc99-9c0b-4ef8-bb6d-6bb9bd380a13',
  'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a12',
  0,
  'When designing databases, it is important to follow established best practices. First, normalize your data to reduce redundancy. Second, use appropriate data types for each column.',
  28,
  '{"chunk_type": "principles"}'::jsonb
),
(
  'b0eebc99-9c0b-4ef8-bb6d-6bb9bd380a14',
  'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a12',
  1,
  'Third, create indexes on frequently queried columns. Fourth, implement proper constraints to maintain data integrity. Fifth, consider performance implications of your design decisions.',
  26,
  '{"chunk_type": "implementation"}'::jsonb
),
(
  'b0eebc99-9c0b-4ef8-bb6d-6bb9bd380a15',
  'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a12',
  2,
  'These practices will help ensure your database is efficient, maintainable, and scalable.',
  14,
  '{"chunk_type": "conclusion"}'::jsonb
),

-- Chunks for "Vector Databases Explained"
(
  'b0eebc99-9c0b-4ef8-bb6d-6bb9bd380a16',
  'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a13',
  0,
  'Vector databases are specialized databases designed to store and query high-dimensional vectors efficiently. They are essential for applications involving machine learning, recommendation systems, and similarity search.',
  29,
  '{"chunk_type": "definition"}'::jsonb
),
(
  'b0eebc99-9c0b-4ef8-bb6d-6bb9bd380a17',
  'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a13',
  1,
  'Popular vector databases include Pinecone, Weaviate, and Chroma. Vector databases use specialized indexing techniques like HNSW (Hierarchical Navigable Small World) and IVF (Inverted File) to enable fast similarity searches across millions of vectors.',
  38,
  '{"chunk_type": "examples"}'::jsonb
); 